x=10
y=5
tong=x+y
hieu=5
tich=x*y
thuong=x/y
print('Tổng_của_hai_số    ', x, '+', y, '=',tong)
print('Hiệu_của_hai_số    ', x, '-', y, '=',hieu)
print('Tích_của_hai_số    ', x, '*', y, '=',tich)
print('Thuong_của_hai_số  ', x, '/', y, '=',thuong)